spring.main.allow-bean-definition-overriding: true

server.port: 7100
management.port: 7101

spring:
    security:
        oauth2:
            client:
                provider:
                    mocklab:
                        authorization-uri: https://oauth.wiremockapi.cloud/oauth/authorize
                        token-uri: https://oauth.wiremockapi.cloud/oauth/token
                        user-info-uri: https://oauth.wiremockapi.cloud/userinfo
                        user-name-attribute: sub
                        jwk-set-uri: https://oauth.wiremockapi.cloud/.well-known/jwks.json

                    wiremock:
                        authorization-uri: http://localhost:8077/oauth/authorize
                        token-uri: http://localhost:8077/oauth/token
                        user-info-uri: http://localhost:8077/userinfo
                        user-name-attribute: sub

                registration:
                    google:
                        clientId: 677624187256-vcp2r9ccsjjhu5diej8a89nu1aac4q4j.apps.googleusercontent.com
                        clientSecret: ${GOOGLE_CLIENT_SECRET}

                    mock-oauth2:
                        provider: mocklab
                        authorization-grant-type: authorization_code
                        scope: email
                        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
                        clientId: mocklab_oauth2
                        clientSecret: whatever

                    mock-oidc:
                        provider: mocklab
                        authorization-grant-type: authorization_code
                        scope: openid, profile, email
                        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
                        clientId: mocklab_oidc
                        clientSecret: whatever

                    wiremock:
                        provider: wiremock
                        authorization-grant-type: authorization_code
                        scope: email
                        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
                        clientId: wm
                        clientSecret: whatever

spring.mustache.expose-request-attributes: true

todo-api.baseurl: http://live-demo.wiremockapi.cloud
backend.http.read-timeout: 30000

paypal.endpoint: https://paypal-demo.wiremockapi.cloud/
#paypal.endpoint: https://api.sandbox.paypal.com/

paypal.client.id: AX7GYdURLc6DOP8d4FZmC8Chduox_EdfVmn_OsoAcgc-FrnrSYD2EFHZebApvq5yQszXc4NhzdXunAD4
paypal.client.secret: xxx

logging:
    level:
        org:
            springframework: DEBUG
